// ============================================================================
// shared/byTheBook.js — the "By the Book" study feature: the visual book
// shelf/ruler, book/session selection, the Listen/Watch/Read session list,
// the presenter and shelf-group systems, and the full admin form for
// editing a book's content.
//
// NOT included here, on purpose, even though it sits right next door in the
// UI: Church Resources (the per-verse resource attachments shown in the main
// Bible reading tab) stayed in app.js — it's a separate feature that just
// happens to share some plumbing (thumbnail resolution, YouTube playback),
// not something exclusive to this screen. Likewise isBookFullyClicked/
// sessionHasClickableResource (the "book_resources_clicked" badge check)
// stayed with the rest of the badge system in app.js, importing what they
// need from here instead.
//
// Depends on quite a bit from elsewhere, reflecting how woven into the rest
// of the app this feature actually is:
//   - core/db.js: createTableAccessor, fetchAllRows
//   - shared/adminUtils.js: makeAdminDragReorder
//   - shared/videoPlayer.js: isDirectVideoUrl, toYouTubeEmbedUrl, openFsvPlayer
//   - app.js: escapeHtml, fixMojibakeText, currentUser, shareBookSession,
//     switchTab/switchStudySubTab, updateStudyNotificationBadges, and the
//     BIBLE_STUDIES_* book-list constants (also needed by Church Resources
//     and the scripture auto-linker, both of which stayed in app.js, so
//     those constants did too rather than moving somewhere only this module
//     could reach). markBookResourceClicked (from shared/records.js, once
//     that existed) is referenced only inside onclick-attribute HTML
//     strings here, never called directly, so it isn't imported at all —
//     same reasoning as shared/audioPlayer.js's controls below.
// Also renders onclick/oninput attributes that reference
// shared/audioPlayer.js's controls (togglePlay, skipAudio, etc.) by name --
// those resolve through the global scope at click time, same as any other
// onclick handler, so this file doesn't need to import them itself.
//     too rather than moving somewhere only this module could reach).
// app.js in turn imports this module's own exports back — another genuine
// circular dependency, handled the same documented way as the one between
// app.js and videoPlayer.js: every usage on both sides is inside a function
// body, never at module-load time, so ES modules' live bindings resolve it
// correctly regardless of which file finishes loading first.
// ============================================================================

import { createTableAccessor, fetchAllRows } from '../core/db.js';
import { makeAdminDragReorder } from './adminUtils.js';
import { isDirectVideoUrl, toYouTubeEmbedUrl, openFsvPlayer } from './videoPlayer.js';
import {
  escapeHtml, fixMojibakeText, currentUser, shareBookSession,
  switchTab, switchStudySubTab, updateStudyNotificationBadges,
  BIBLE_STUDIES_BOOK_ORDER, BIBLE_STUDIES_DATA, BIBLE_STUDIES_DEFAULT_COLORS,
  BIBLE_STUDIES_DEFAULT_HEIGHTS, OT_BOOK_COUNT
} from '../app.js';

    export let activeBibleStudyBook = null;

    // Books of the Bible: current session filters.
    // activeStudyTypeFilter is really the active VIEW — Listen (audio), Watch (video), or
    // Read (print) — exactly one is always selected, defaulting to 'audio' (Listen).
    // activeStudyPresenterFilter is an optional additional filter (null = no presenter filter).
    // Both are reset whenever a different book is selected.
    export let activeStudyPresenterFilter = null;
    export let activeStudyTypeFilter = 'audio';

    // A setter, rather than letting app.js assign these two directly — an
    // imported binding is a read-only view from the importing module's side,
    // so app.js's shared-link handler (which needs to override both when
    // jumping straight to a specific session) has to go through this instead.
    export function setActiveStudyFilters(typeFilter, presenterFilter) {
      activeStudyTypeFilter = typeFilter;
      activeStudyPresenterFilter = presenterFilter;
    }

    // Admin-added book content, loaded from the `bible_study_books` table (see
    // loadBibleStudyBooksFromDB below) and keyed by book title. A book saved here takes
    // priority over the hand-written BIBLE_STUDIES_DATA entry of the same name — this is
    // what lets admins add/edit content from the "Manage Content" screen instead of
    // hand-editing this file (and risking exactly the kind of typo that broke the app
    // last time). Books never touched by an admin just keep using BIBLE_STUDIES_DATA.
    //
    // One-time setup: this table needs to exist in Supabase before Manage Content will
    // save anything. Run once in the SQL editor:
    //
    //   create table if not exists bible_study_books (
    //     id bigint generated by default as identity primary key,
    //     book text unique not null,
    //     color text,
    //     height int,
    //     live boolean not null default false,
    //     shelf_group_id bigint references book_shelf_groups(id) on delete set null,
    //     presenters jsonb not null default '[]'::jsonb,
    //     sessions jsonb not null default '[]'::jsonb,
    //     updated_at timestamptz not null default now()
    //   );
    //
    // (see book_shelf_groups_migration.sql for the shelf_group_id column + the
    // book_shelf_groups table itself, if this app predates that feature)
    //
    // If church_resources has row-level security policies, mirror the same read/write
    // policies onto this table (admin status is enforced client-side here, same as the
    // existing church_resources add/delete buttons).
    export let bibleStudyDbBooks = {};
    export const bibleStudyBooksTable = createTableAccessor('bible_study_books');

    // ------------------------------------------------------------------
    // SHELF GROUPS — lets an admin put several books' spines under one shared
    // color + height ("Major Prophets", "Gospels", etc.) instead of setting
    // each book's color/height one at a time. A book's own row just stores
    // which group it belongs to (shelf_group_id); the actual color/height
    // live on the group itself, so editing them once (from ANY book in that
    // group, in Manage Content) updates every book in the group at once —
    // see getBibleStudyBookConfig, which resolves a grouped book's color/
    // height from here rather than from the book's own row. Run once in the
    // SQL editor (see book_shelf_groups_migration.sql for the full migration,
    // including the bible_study_books.shelf_group_id column added above):
    //
    //   create table if not exists book_shelf_groups (
    //     id bigint generated by default as identity primary key,
    //     name text unique not null,
    //     color text not null,
    //     height int not null,
    //     updated_at timestamptz not null default now()
    //   );
    //   alter table book_shelf_groups disable row level security;
    //
    export let bookShelfGroupsList = []; // [{ id, name, color, height }]
    export let bibleStudyRulerScrollBound = false; // whether the shelf's scroll listener (which keeps the ruler in sync) has been attached yet
    // The OT/NT dimension lines' real span, in the same scroll-coordinate space
    // as shelf.scrollLeft — kept up to date by renderBibleStudyRuler() and read
    // by the (once-bound, long-lived) scroll listener so the "OLD TESTAMENT"/
    // "NEW TESTAMENT" labels below can always be repositioned against the
    // CURRENT shelf/section sizes, not whatever they happened to be the one
    // time the listener was attached.
    export let bibleStudyRulerMetrics = { otStart: 0, otWidth: 0, ntStart: 0, ntWidth: 0 };

    export const bookShelfGroupsTable = createTableAccessor('book_shelf_groups');

    export async function loadBookShelfGroups() {
      try {
        bookShelfGroupsList = await fetchAllRows('book_shelf_groups', 'id, name, color, height', null, 'name');
      } catch (e) {
        // Table may not exist yet — every book just falls back to its own color/height
        // (or the built-in defaults) until it's created; see the comment above.
        console.error('Error loading book shelf groups:', e.message);
        bookShelfGroupsList = [];
      }
    }

    // Updates a shelf group's shared color/height. Every book assigned to this
    // group picks it up immediately (getBibleStudyBookConfig resolves a grouped
    // book's color/height from the group, not the book's own row) — that
    // propagation IS the point of grouping books together. Returns true/false
    // so callers can bail out of the rest of a save on failure.
    export async function updateBookShelfGroupColorHeight(groupId, color, height) {
      const { data, error } = await bookShelfGroupsTable.update(
        groupId,
        { color, height, updated_at: new Date().toISOString() },
        'id, name, color, height'
      );
      if (error) {
        console.error('Error updating shelf group:', error.message);
        alert('Could not update the shelf group: ' + error.message);
        return false;
      }
      const idx = bookShelfGroupsList.findIndex(g => g.id === groupId);
      if (idx !== -1) bookShelfGroupsList[idx] = data; else bookShelfGroupsList.push(data);
      return true;
    }

    // ------------------------------------------------------------------
    // STUDY PRESENTERS — a small reusable directory of presenter name/photo
    // pairs, so the admin can pick an existing presenter from a dropdown
    // instead of retyping/repasting the same photo URL for every book they
    // appear in. New presenters (typed in by hand) are added to this table
    // automatically the next time the book they're on is saved, so they show
    // up in the dropdown for every future book. Run once in the SQL editor:
    //
    //   create table if not exists study_presenters (
    //     id bigint generated by default as identity primary key,
    //     name text not null unique,
    //     photo_url text not null,
    //     created_at timestamptz not null default now()
    //   );
    //   alter table study_presenters disable row level security;
    //
    export let studyPresentersList = []; // [{ id, name, photo_url }]
    export let studyPresentersLoadError = null; // set if the table couldn't be read (missing table, RLS, etc.)

    export async function loadStudyPresenters() {
      studyPresentersLoadError = null;
      try {
        studyPresentersList = await fetchAllRows('study_presenters', 'id, name, photo_url', null, 'name');
      } catch (e) {
        // Table may not exist yet, or Row Level Security is blocking reads — surface this
        // in the dropdown itself (see populateStudyPresenterDropdowns) instead of only the
        // console, since an admin has no reason to check dev tools otherwise.
        console.error('Error loading study presenters:', e.message);
        studyPresentersLoadError = e.message;
        studyPresentersList = [];
      }
    }

    export const studyPresentersTable = createTableAccessor('study_presenters');

    // Adds a presenter to the reusable directory if it's not already there (matched by
    // name, case-insensitive). Safe to call every time a book is saved.
    // Returns true on success, false on a real failure (e.g. an RLS block on writes) so
    // callers can surface it instead of it disappearing into the console.
    export async function upsertStudyPresenter(name, photo) {
      const cleanName = (name || '').trim();
      const cleanPhoto = (photo || '').trim();
      if (!cleanName || !cleanPhoto) return true;
      const existing = studyPresentersList.find(p => p.name.toLowerCase() === cleanName.toLowerCase());
      if (existing) {
        if (existing.photo_url !== cleanPhoto) {
          // Keep the directory's photo current if it was edited on this book.
          const { error } = await studyPresentersTable.update(existing.id, { photo_url: cleanPhoto });
          if (!error) { existing.photo_url = cleanPhoto; return true; }
          console.error('Error updating study presenter photo:', error.message);
          return false;
        }
        return true;
      }
      try {
        const { data, error } = await studyPresentersTable.insert({ name: cleanName, photo_url: cleanPhoto }, 'id, name, photo_url');
        if (error) throw error;
        studyPresentersList.push(data);
        studyPresentersList.sort((a, b) => a.name.localeCompare(b.name));
        return true;
      } catch (e) {
        console.error('Error adding study presenter:', e.message);
        return false;
      }
    }

    // One-time backfill: if the directory is empty (freshly created table), seed it from
    // every presenter already used across all books — hardcoded and DB-saved alike —
    // so the dropdown isn't empty the very first time an admin opens this view. If writes
    // fail (e.g. Row Level Security blocking inserts while still allowing reads — which
    // shows up as "table reads fine but stays empty"), that's surfaced the same way a
    // read failure is, via studyPresentersLoadError, instead of only the console.
    export async function seedStudyPresentersFromExistingBooksIfEmpty() {
      if (studyPresentersList.length > 0) return;
      const seen = new Map(); // name (lowercase) -> { name, photo }
      BIBLE_STUDIES_BOOK_ORDER.forEach((title, index) => {
        const cfg = getBibleStudyBookConfig(title, index);
        (cfg.presenters || []).forEach(p => {
          if (p && p.name && p.photo && !seen.has(p.name.toLowerCase())) seen.set(p.name.toLowerCase(), p);
        });
        (cfg.sessions || []).forEach(s => {
          if (s && s.presenter && s.presenter.name && s.presenter.photo && !seen.has(s.presenter.name.toLowerCase())) {
            seen.set(s.presenter.name.toLowerCase(), s.presenter);
          }
        });
      });
      if (seen.size === 0) return;
      let failures = 0;
      for (const p of seen.values()) {
        const ok = await upsertStudyPresenter(p.name, p.photo);
        if (!ok) failures++;
      }
      if (failures > 0 && studyPresentersList.length === 0) {
        studyPresentersLoadError = `Found ${seen.size} presenter(s) in your existing books, but saving ${failures} of them to the "study_presenters" table failed — most likely Row Level Security is blocking writes even though reads work. Try running: alter table study_presenters disable row level security; then reopen this screen, or add presenters manually below in the meantime.`;
      }
    }

    // Populates every "Choose existing presenter" dropdown currently in the book admin
    // form with the current directory contents.
    export function populateStudyPresenterDropdowns() {
      let placeholder = 'Choose an existing presenter…';
      if (studyPresentersLoadError) {
        placeholder = '⚠ Could not load presenters — see below';
      } else if (studyPresentersList.length === 0) {
        placeholder = 'No presenters saved yet — add one below';
      }
      document.querySelectorAll('.study-presenter-picker').forEach(select => {
        const current = select.value;
        select.innerHTML = `<option value="">${placeholder}</option>` +
          studyPresentersList.map(p => `<option value="${p.id}">${(p.name || '').replace(/</g, '&lt;')}</option>`).join('');
        select.value = current && studyPresentersList.some(p => String(p.id) === current) ? current : '';
      });

      document.querySelectorAll('.study-presenter-picker-error-note').forEach(note => {
        if (studyPresentersLoadError) {
          note.style.display = 'block';
          note.innerText = `Presenter list failed to load: ${studyPresentersLoadError}. This is usually because the "study_presenters" table hasn't been created yet, or Row Level Security is blocking reads — see the comment above loadStudyPresenters() in this file for the setup SQL.`;
        } else {
          note.style.display = 'none';
        }
      });
    }

    export async function loadBibleStudyBooksFromDB() {
      try {
        const rows = await fetchAllRows('bible_study_books', 'id, book, color, height, live, shelf_group_id, presenters, sessions');
        const map = {};
        rows.forEach(r => {
          map[r.book] = {
            dbId: r.id,
            color: r.color,
            height: r.height,
            live: !!r.live,
            shelfGroupId: r.shelf_group_id,
            presenters: Array.isArray(r.presenters) ? r.presenters : [],
            sessions: Array.isArray(r.sessions) ? r.sessions.map(s => ({ ...s, title: fixMojibakeText(s.title || '') })) : []
          };
        });
        bibleStudyDbBooks = map;
      } catch (e) {
        // Table may not exist yet (first-time setup) — fall back to BIBLE_STUDIES_DATA only.
        console.error('Error loading Books of the Bible admin content:', e.message);
      }
    }

    export function getBibleStudyBookConfig(title, index) {
      const dbRow = bibleStudyDbBooks[title];
      const custom = dbRow || BIBLE_STUDIES_DATA[title];
      // Supports both the older single `presenter` field (existing books) and the
      // newer `presenters` array (for books with more than one presenter) — always
      // normalized to an array here so the renderer only has to handle one shape.
      let presenters = [];
      if (custom) {
        if (Array.isArray(custom.presenters)) {
          presenters = custom.presenters;
        } else if (custom.presenter) {
          presenters = [custom.presenter];
        }
      }
      // A book in a shelf group takes its color/height from the group (shared
      // across every book in it) rather than from its own row — that's what
      // makes editing a group's color update every book in it at once.
      const shelfGroupId = dbRow ? dbRow.shelfGroupId : null;
      const shelfGroup = (shelfGroupId != null) ? bookShelfGroupsList.find(g => g.id === shelfGroupId) : null;
      return {
        title,
        dbId: dbRow ? dbRow.dbId : null,
        shelfGroupId: shelfGroupId,
        color: (shelfGroup && shelfGroup.color) || (custom && custom.color) || BIBLE_STUDIES_DEFAULT_COLORS[index % BIBLE_STUDIES_DEFAULT_COLORS.length],
        height: (shelfGroup && shelfGroup.height) || (custom && custom.height) || BIBLE_STUDIES_DEFAULT_HEIGHTS[index % BIBLE_STUDIES_DEFAULT_HEIGHTS.length],
        live: !!(custom && custom.live),
        presenters: presenters,
        sessions: custom ? (custom.sessions || []) : []
      };
    }

    // Canonical display order for the color-code legend — traditional section
    // groupings rather than alphabetical, so the legend reads the way these
    // testaments are conventionally divided. A group whose name matches one of
    // these (case-insensitively) sorts into that position; any other group
    // name (a custom grouping an admin made up) just falls in after these,
    // alphabetically.
    export const OT_GROUP_ORDER = ['The Law', 'The Former Prophets', 'The Writings', 'The Major Prophets', 'The Minor Prophets'];
    export const NT_GROUP_ORDER = ['The Gospels & Acts', 'The Epistles of Paul', 'The General Epistles', 'Revelation'];

    export function sortGroupsByCanonicalOrder(groups, order) {
      function rank(name) {
        const idx = order.findIndex(o => o.toLowerCase() === name.trim().toLowerCase());
        return idx === -1 ? order.length : idx;
      }
      return groups.slice().sort((a, b) => {
        const ra = rank(a.name), rb = rank(b.name);
        if (ra !== rb) return ra - rb;
        return a.name.localeCompare(b.name);
      });
    }

    // Color-code reference shown above the shelf: one swatch per named shelf
    // group that has at least one member book in that testament (a book's own
    // individual color isn't listed here — only groups act as a shared "code",
    // since that's the only case where the same color maps to more than one
    // book). Re-run this any time the shelf itself re-renders so it always
    // matches the current groups.
    export function renderBibleStudyColorLegend() {
      const otContainer = document.getElementById('bible-study-color-codes-ot');
      const ntContainer = document.getElementById('bible-study-color-codes-nt');
      if (!otContainer || !ntContainer) return;

      const otGroupIds = new Set();
      const ntGroupIds = new Set();
      BIBLE_STUDIES_BOOK_ORDER.forEach((title, i) => {
        const cfg = getBibleStudyBookConfig(title, i);
        if (cfg.shelfGroupId != null) {
          (i < OT_BOOK_COUNT ? otGroupIds : ntGroupIds).add(cfg.shelfGroupId);
        }
      });

      function buildItemsHtml(groupIds, order) {
        if (groupIds.size === 0) {
          return '<div class="bible-study-color-code-empty">No color groups yet — assign one in Manage Content.</div>';
        }
        const groups = sortGroupsByCanonicalOrder(bookShelfGroupsList.filter(g => groupIds.has(g.id)), order);
        return groups.map(g => `
          <div class="bible-study-color-code-item">
            <span class="bible-study-color-code-swatch" style="background:${g.color};"></span>
            <span>${escapeHtml(g.name)}</span>
          </div>`).join('');
      }

      otContainer.innerHTML = buildItemsHtml(otGroupIds, OT_GROUP_ORDER);
      ntContainer.innerHTML = buildItemsHtml(ntGroupIds, NT_GROUP_ORDER);
    }

    // Pixel-aligns the two dimension-line rulers to the actual spines below
    // them (Genesis→Malachi, Matthew→Revelation) and keeps them sliding in
    // lockstep with the shelf's own horizontal scroll. The ruler track is
    // sized to the shelf's full scrollWidth and each line is positioned at
    // that book's real on-shelf coordinates, so it always starts flush with
    // the left edge of its first book and ends flush with the right edge of
    // its last — no matter how far the shelf has been scrolled.
    // Draws one dimension line's full width — both end ticks plus the
    // connecting rule — into its <svg>, sized via the width/height
    // ATTRIBUTES (no viewBox, no CSS-driven stretching) so 1 SVG unit is
    // exactly 1 CSS pixel with zero scale transform involved. Combined with
    // shape-rendering="crispEdges" on the root <svg> (set once in the HTML),
    // every stroke edge — both ticks included — snaps to the same device
    // pixel grid, so they always render at an identical width, unlike two
    // separate CSS box-model elements which can each get rounded slightly
    // differently by the browser's own layout engine.
    export function drawDimLineSvg(svgId, width) {
      const svg = document.getElementById(svgId);
      if (!svg) return;
      const h = 15;
      const w = Math.max(0, Math.round(width));
      svg.setAttribute('width', w);
      svg.setAttribute('height', h);
      if (w === 0) { svg.innerHTML = ''; return; }
      const stroke = 'style="stroke:var(--primary-color);"';
      svg.innerHTML =
        `<line x1="1" y1="0" x2="1" y2="${h}" stroke-width="2" ${stroke}></line>` +
        `<line x1="${w - 1}" y1="0" x2="${w - 1}" y2="${h}" stroke-width="2" ${stroke}></line>` +
        `<line x1="0" y1="${h / 2}" x2="${w}" y2="${h / 2}" stroke-width="2.5" ${stroke}></line>`;
    }

    // Keeps a testament's "OLD TESTAMENT"/"NEW TESTAMENT" label centered in
    // whatever part of its dimension line is actually scrolled into view,
    // instead of centered on the line's full width. On a wide desktop
    // viewport the whole line (and the label with it) usually fits on screen
    // at once, so this rarely visibly matters there — but on a narrow mobile
    // screen the shelf can be scrolled across a line many times the
    // viewport's own width, and a label fixed to the line's midpoint then
    // sits far outside whatever sliver is currently visible, effectively
    // never showing up. Hidden entirely (rather than clamped to an edge)
    // when the section isn't in view at all, so it doesn't sit pinned to the
    // wrong content while the user is scrolled elsewhere.
    export function positionDimLabel(labelId, sectionStart, sectionWidth, viewportWidth, scrollLeft) {
      const label = document.getElementById(labelId);
      if (!label) return;
      const sectionEnd = sectionStart + sectionWidth;
      const visibleStart = Math.max(sectionStart, scrollLeft);
      const visibleEnd = Math.min(sectionEnd, scrollLeft + viewportWidth);
      if (sectionWidth <= 0 || visibleStart >= visibleEnd) {
        label.style.display = 'none';
        return;
      }
      label.style.display = '';
      let midpoint = (visibleStart + visibleEnd) / 2;

      // The label's own rendered width isn't factored into that midpoint, so on
      // a narrow (mobile) viewport — where only a sliver of this testament's
      // line is scrolled into view — centering on that sliver can push half the
      // label past the viewport's own edge, where .bible-study-ruler-viewport's
      // overflow:hidden then clips it (e.g. "OLD TESTAMENT" bleeding off-screen
      // as just "TESTAMENT"). Clamp the label's center so its full width stays
      // inside the viewport whenever there's room to. label.offsetWidth forces a
      // layout read here, but this only runs on render/scroll for two labels.
      const halfLabelWidth = label.offsetWidth / 2;
      const viewportMin = scrollLeft + halfLabelWidth;
      const viewportMax = scrollLeft + viewportWidth - halfLabelWidth;
      if (viewportMin <= viewportMax) {
        midpoint = Math.min(Math.max(midpoint, viewportMin), viewportMax);
      }

      label.style.left = Math.round(midpoint - sectionStart) + 'px';
    }

    // Re-reads the shelf's current scroll position (and the last metrics
    // renderBibleStudyRuler computed) to reposition both testament labels —
    // called on every render AND on every scroll tick, since which slice of
    // each line is visible changes continuously as the shelf scrolls.
    export function updateBibleStudyDimLabels() {
      const shelf = document.getElementById('bible-study-shelf');
      const viewport = document.getElementById('bible-study-ruler-viewport');
      if (!shelf || !viewport) return;
      const viewportWidth = viewport.getBoundingClientRect().width;
      const scrollLeft = shelf.scrollLeft;
      positionDimLabel('bible-study-dim-label-ot', bibleStudyRulerMetrics.otStart, bibleStudyRulerMetrics.otWidth, viewportWidth, scrollLeft);
      positionDimLabel('bible-study-dim-label-nt', bibleStudyRulerMetrics.ntStart, bibleStudyRulerMetrics.ntWidth, viewportWidth, scrollLeft);
    }

    export function renderBibleStudyRuler() {
      const shelf = document.getElementById('bible-study-shelf');
      const track = document.getElementById('bible-study-ruler-track');
      const viewport = document.getElementById('bible-study-ruler-viewport');
      const leadSpacer = document.getElementById('bible-study-ruler-lead');
      const midSpacer = document.getElementById('bible-study-ruler-mid');
      const otSection = document.getElementById('bible-study-legend-section-ot');
      const ntSection = document.getElementById('bible-study-legend-section-nt');
      if (!shelf || !track || !viewport || !leadSpacer || !midSpacer || !otSection || !ntSection) return;

      function spineEl(title) {
        const i = BIBLE_STUDIES_BOOK_ORDER.indexOf(title);
        return i === -1 ? null : document.getElementById(`book-spine-${i}`);
      }
      const genesisEl = spineEl('Genesis'), malachiEl = spineEl('Malachi');
      const matthewEl = spineEl('Matthew'), revelationEl = spineEl('Revelation');
      if (!genesisEl || !malachiEl || !matthewEl || !revelationEl) {
        // Shouldn't normally happen (the book order is a fixed constant) — hide
        // the ruler rather than show something misaligned.
        viewport.style.display = 'none';
        return;
      }
      viewport.style.display = '';

      // Each section (dimension line + its color-code swatches, stacked) and
      // the spacers before/between them are sized to the real on-shelf pixel
      // span of their boundary books, so the line, the swatches below it, AND
      // the gap that precedes them all sit exactly where those books are —
      // and, since they're laid out in normal flow inside one flex track that
      // gets shifted by shelf's own scrollLeft, they slide along with the
      // shelf as a single unit rather than needing separate tracking.
      const shelfRect = shelf.getBoundingClientRect();
      function left(el) { return el.getBoundingClientRect().left - shelfRect.left + shelf.scrollLeft; }
      function right(el) { return el.getBoundingClientRect().right - shelfRect.left + shelf.scrollLeft; }

      // Rounded to whole pixels: getBoundingClientRect can return fractional
      // values (sub-pixel flex layout, device pixel ratio), and a fractional
      // width/position on a thin 2px tick lands it on a half-pixel boundary,
      // which the browser then anti-aliases — making that one tick render
      // visibly thinner/blurrier than its neighbor. Whole pixels keep both
      // ticks on the same crisp footing.
      const genesisLeft = Math.round(left(genesisEl));
      const malachiRight = Math.round(right(malachiEl));
      const matthewLeft = Math.round(left(matthewEl));
      const revelationRight = Math.round(right(revelationEl));

      const otWidth = Math.max(0, malachiRight - genesisLeft);
      const ntWidth = Math.max(0, revelationRight - matthewLeft);

      leadSpacer.style.width = Math.max(0, genesisLeft) + 'px';
      otSection.style.width = otWidth + 'px';
      midSpacer.style.width = Math.max(0, matthewLeft - malachiRight) + 'px';
      ntSection.style.width = ntWidth + 'px';

      drawDimLineSvg('bible-study-dim-line-ot-svg', otWidth);
      drawDimLineSvg('bible-study-dim-line-nt-svg', ntWidth);

      bibleStudyRulerMetrics = {
        otStart: Math.max(0, genesisLeft),
        otWidth: otWidth,
        ntStart: matthewLeft,
        ntWidth: ntWidth
      };

      track.style.transform = `translateX(${-Math.round(shelf.scrollLeft)}px)`;
      updateBibleStudyDimLabels();

      if (!bibleStudyRulerScrollBound) {
        shelf.addEventListener('scroll', () => {
          const t = document.getElementById('bible-study-ruler-track');
          if (t) t.style.transform = `translateX(${-Math.round(shelf.scrollLeft)}px)`;
          updateBibleStudyDimLabels();
        });
        bibleStudyRulerScrollBound = true;
      }
    }

    export function renderBibleStudyShelf() {
      const shelf = document.getElementById('bible-study-shelf');
      const select = document.getElementById('bible-study-book-select');
      if (!shelf) return;

      const adminBtn = document.getElementById('book-admin-entry-btn');
      if (adminBtn) adminBtn.style.display = (currentUser && currentUser.isAdmin) ? 'inline-block' : 'none';

      let shelfHtml = '';
      let optionsHtml = '<option value="">Choose a book…</option>';

      BIBLE_STUDIES_BOOK_ORDER.forEach((title, i) => {
        const cfg = getBibleStudyBookConfig(title, i);
        const isSelected = activeBibleStudyBook === title;
        const safeTitle = title.replace(/'/g, "\\'");
        shelfHtml += `
          <div class="book-spine ${isSelected ? 'selected' : ''} ${cfg.live ? '' : 'not-live'}"
               style="height:${cfg.height}px; background:${cfg.color};"
               title="${title}${cfg.live ? '' : ' (coming soon)'}"
               onclick="handleBookSpineClick('${safeTitle}')"
               id="book-spine-${i}">
            <span class="book-spine-label">${title}</span>
          </div>`;
        optionsHtml += `<option value="${title}" ${isSelected ? 'selected' : ''}>${title}</option>`;
      });

      shelf.innerHTML = shelfHtml;
      if (select) select.innerHTML = optionsHtml;
      renderBibleStudyColorLegend();
      renderBibleStudyRuler();
    }

    export function handleBookSpineClick(title) {
      selectBibleStudyBook(title, false);
    }

    export function selectBibleStudyBookFromDropdown(title) {
      if (!title) return;
      selectBibleStudyBook(title, true);
    }

    export function selectBibleStudyBook(title, scrollToIt) {
      const index = BIBLE_STUDIES_BOOK_ORDER.indexOf(title);
      if (index === -1) return;
      const cfg = getBibleStudyBookConfig(title, index);

      // A newly-selected book starts on the Listen view with no presenter filter applied.
      activeStudyPresenterFilter = null;
      activeStudyTypeFilter = 'audio';

      activeBibleStudyBook = title;
      renderBibleStudyShelf();

      if (scrollToIt) {
        const el = document.getElementById(`book-spine-${index}`);
        if (el) el.scrollIntoView({ behavior: 'smooth', inline: 'center', block: 'nearest' });
      }

      renderBibleStudyInfoPanel(cfg);
    }
    export function openBookVideoPlayer(bookTitle, originalIndex) {
      const cfg = getBibleStudyBookConfig(bookTitle, 0);
      const session = (cfg.sessions || [])[originalIndex];
      if (!session || !session.video) return;
      openFsvPlayer([{ label: session.title, url: session.video }], 0, cfg.title);
    }

    // A session's content type — used for the Audio/Video/Print filter. An explicit
    // `type` always wins; otherwise it's inferred from whichever content field is set,
    // so existing audio/video sessions keep working without any data changes.
    export function getSessionType(s) {
      if (s.type) return s.type;
      if (s.video) return 'video';
      if (s.article) return 'print';
      if (s.audio) return 'audio';
      return 'other';
    }

    // "Print (Study Guide)" is its own session type (so the admin form and edit view can
    // tell it apart from a plain article), but for the reader-facing Audio/Video/Print
    // filter it counts as Print, same bucket as a regular article.
    export function getSessionFilterType(s) {
      const t = getSessionType(s);
      return t === 'study_guide' ? 'print' : t;
    }

    // Which presenter a session is attributed to, for the presenter filter. A session
    // can name its own presenter (`s.presenter`, for books with more than one); otherwise
    // it's attributed to the book's single presenter, when there's exactly one.
    export function getSessionPresenterName(s, cfg) {
      if (s.presenter) return s.presenter.name;
      if (cfg.presenters && cfg.presenters.length === 1) return cfg.presenters[0].name;
      return null;
    }

    export function toggleStudyPresenterFilter(name) {
      activeStudyPresenterFilter = (activeStudyPresenterFilter === name) ? null : name;
      renderBibleStudyInfoPanel(getBibleStudyBookConfig(activeBibleStudyBook, BIBLE_STUDIES_BOOK_ORDER.indexOf(activeBibleStudyBook)));
    }

    // Switches the Listen/Watch/Read view. Unlike the presenter filter this isn't a
    // toggle — exactly one view is always active, so clicking a view just selects it.
    export function selectStudyView(type) {
      activeStudyTypeFilter = type;
      renderBibleStudyInfoPanel(getBibleStudyBookConfig(activeBibleStudyBook, BIBLE_STUDIES_BOOK_ORDER.indexOf(activeBibleStudyBook)));
    }

    export function clearStudyPresenterFilter() {
      activeStudyPresenterFilter = null;
      renderBibleStudyInfoPanel(getBibleStudyBookConfig(activeBibleStudyBook, BIBLE_STUDIES_BOOK_ORDER.indexOf(activeBibleStudyBook)));
    }

    export function renderBibleStudyInfoPanel(cfg) {
      const panel = document.getElementById('bible-study-info-panel');
      if (!panel) return;
      panel.style.display = 'block';

      if (!cfg.live) {
        panel.innerHTML = `
          <div style="text-align:center; color:var(--text-muted); padding: 10px 0;">
            <div style="font-family: var(--font-heading); font-size:24px; color:var(--text-main); margin-bottom:6px;">${cfg.title}</div>
            <div>This Bible Study isn't available yet — check back soon!</div>
          </div>`;
        return;
      }

      const allSessions = cfg.sessions || [];

      // Clicking a presenter (when a book has more than one) filters the list below to
      // just their sessions/articles; clicking the same one again clears the filter.
      const presenterHtml = (cfg.presenters && cfg.presenters.length > 0) ? `
        <div class="study-hscroll" style="gap:18px; margin-bottom:16px;">
          ${cfg.presenters.map(p => {
            const clickable = cfg.presenters.length > 1;
            const isActive = activeStudyPresenterFilter === p.name;
            const safeName = p.name.replace(/'/g, "\\'");
            return `
            <div class="${clickable ? 'study-presenter-chip' : ''} ${clickable && isActive ? 'active' : ''}"
                 style="display:flex; align-items:center; gap:10px; flex-shrink:0; white-space:nowrap; ${clickable ? 'cursor:pointer;' : ''}"
                 ${clickable ? `onclick="toggleStudyPresenterFilter('${safeName}')" title="Filter by ${p.name.replace(/"/g, '&quot;')}"` : ''}>
              <img src="${p.photo}" alt="${p.name}" style="width:56px; height:56px; border-radius:50%; object-fit:cover; border:2px solid ${clickable && isActive ? 'var(--primary-color)' : 'var(--border-color)'}; flex-shrink:0;">
              <div>
                <div style="font-size:12px; color:var(--text-muted);">Presented by</div>
                <div style="font-weight:700; color:var(--text-main);">${p.name}</div>
              </div>
            </div>`;
          }).join('')}
        </div>` : '';

      // View tabs — Listen (audio) / Watch (video) / Read (print). Exactly one is always
      // active (defaults to Listen — see activeStudyTypeFilter's declaration); a view with
      // no sessions here is dimmed but still selectable, showing an empty-state message.
      const typeLabels = { audio: 'Listen', video: 'Watch', print: 'Read' };
      const typeNouns = { audio: 'audio', video: 'video', print: 'print' };
      const typeCounts = { audio: 0, video: 0, print: 0 };
      allSessions.forEach(s => { const t = getSessionFilterType(s); if (typeCounts[t] !== undefined) typeCounts[t]++; });
      const typeFilterHtml = allSessions.length > 0 ? `
        <div class="study-hscroll" style="gap:8px; margin-bottom:16px;">
          ${Object.keys(typeLabels).map(t => {
            const count = typeCounts[t];
            const isActive = activeStudyTypeFilter === t;
            const empty = count === 0;
            return `<button type="button" class="study-filter-chip ${isActive ? 'active' : ''} ${empty ? 'disabled' : ''}" style="flex-shrink:0; white-space:nowrap;" onclick="selectStudyView('${t}')">${typeLabels[t]}${count ? ` (${count})` : ''}</button>`;
          }).join('')}
        </div>` : '';

      const sessionsOfCurrentView = allSessions.filter(s => getSessionFilterType(s) === activeStudyTypeFilter);
      const visibleSessions = sessionsOfCurrentView.filter(s => {
        if (activeStudyPresenterFilter && getSessionPresenterName(s, cfg) !== activeStudyPresenterFilter) return false;
        return true;
      });

      let sessionsHtml;
      if (allSessions.length === 0) {
        sessionsHtml = `<div style="color:var(--text-muted); font-size:13px;">No sessions listed yet.</div>`;
      } else if (visibleSessions.length === 0 && sessionsOfCurrentView.length > 0) {
        // Sessions exist for this view, but the presenter filter is hiding all of them.
        sessionsHtml = `<div style="color:var(--text-muted); font-size:13px;">Nothing matches that filter. <button type="button" onclick="clearStudyPresenterFilter()" style="background:none; border:none; color:var(--primary-color); font-weight:600; cursor:pointer; text-decoration:underline; padding:0; font-family:'Plus Jakarta Sans', sans-serif; font-size:13px;">Clear presenter filter</button></div>`;
      } else if (visibleSessions.length === 0) {
        sessionsHtml = `<div style="color:var(--text-muted); font-size:13px;">No ${typeNouns[activeStudyTypeFilter]} content for this book yet.</div>`;
      } else {
        sessionsHtml = visibleSessions.map((s, i) => {
          const type = getSessionType(s);
          const originalIndex = allSessions.indexOf(s);
          const safeBookTitle = cfg.title.replace(/'/g, "\\'");
          let mediaHtml;
          if (type === 'video' && s.video) {
            const embedUrl = isDirectVideoUrl(s.video) || toYouTubeEmbedUrl(s.video);
            if (embedUrl) {
              // Opens the shared full-screen video player (see openBookVideoPlayer)
              // instead of embedding an inline iframe here.
              mediaHtml = `
                <button type="button" onclick="markBookResourceClicked('${safeBookTitle}', ${originalIndex}); openBookVideoPlayer('${safeBookTitle}', ${originalIndex});" style="display:flex; align-items:center; gap:10px; width:100%; background: linear-gradient(135deg, #6366f1 0%, #a855f7 100%); border:none; padding:14px; border-radius:8px; cursor:pointer; color:#fff; box-sizing:border-box; font-family:'Plus Jakarta Sans', sans-serif;">
                  <span style="display:flex; align-items:center; justify-content:center; width:34px; height:34px; border-radius:50%; background:rgba(255,255,255,0.2); flex-shrink:0;">
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="#fff"><polygon points="6 4 20 12 6 20 6 4"></polygon></svg>
                  </span>
                  <span style="font-weight:700; font-size:13.5px;">Watch Video</span>
                </button>`;
            } else {
              // Not a recognized YouTube link (or the ID couldn't be parsed out of it) —
              // show a working link instead of a player that would fail with a YouTube
              // "Video player configuration error".
              mediaHtml = `
                <a href="${s.video}" target="_blank" rel="noopener" onclick="markBookResourceClicked('${safeBookTitle}', ${originalIndex});" style="display:flex; align-items:center; gap:10px; background: var(--bg-color); border:1px solid var(--border-color); padding:10px 14px; border-radius:8px; text-decoration:none; color:var(--text-main); max-width:100%; box-sizing:border-box;">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--primary-color)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="flex-shrink:0;"><polygon points="23 7 16 12 23 17 23 7"></polygon><rect x="1" y="5" width="15" height="14" rx="2" ry="2"></rect></svg>
                  <span style="font-weight:600; font-size:13px;">Watch video (opens in a new tab) — this link couldn't be embedded directly</span>
                </a>`;
            }
          } else if (s.playerHtml) {
            mediaHtml = s.playerHtml;
          } else if (type === 'print' || type === 'study_guide') {
            const isStudyGuide = type === 'study_guide';
            const articleUrl = s.article || '#';
            mediaHtml = articleUrl && articleUrl !== '#' ? `
              <a href="${articleUrl}" target="_blank" rel="noopener" onclick="markBookResourceClicked('${safeBookTitle}', ${originalIndex});" style="display:flex; align-items:center; gap:10px; background: var(--bg-color); border:1px solid var(--border-color); padding:10px 14px; border-radius:8px; text-decoration:none; color:var(--text-main); max-width:100%; box-sizing:border-box;">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="var(--primary-color)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="flex-shrink:0;">${isStudyGuide ? '<path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path>' : '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line>'}</svg>
                <span style="font-weight:600; font-size:13px;">${isStudyGuide ? 'Read Study Guide' : 'Read Article'}</span>
              </a>` : `<div style="color:var(--text-muted); font-size:12px;">${isStudyGuide ? 'Study guide' : 'Article'} coming soon.</div>`;
          } else if (type === 'audio' && s.audio) {
            const safeAudioTitle = `${cfg.title} • ${s.title || 'Audio'}`.replace(/"/g, '&quot;');
            mediaHtml = `
              <div style="display: flex; align-items: center; background: linear-gradient(135deg, #6366f1 0%, #a855f7 100%); padding: 10px 14px; border-radius: 8px; gap: 8px; color: #fff; max-width: 100%; box-sizing: border-box;">
                <audio id="audio-player-${i}" data-media-title="${safeAudioTitle}" src="${s.audio}" preload="metadata" ontimeupdate="updateProgress(${i})" onloadedmetadata="initAudio(${i})" onended="resetPlayButton(${i})"></audio>
                <button type="button" onclick="togglePlay(${i}); markBookResourceClicked('${safeBookTitle}', ${originalIndex});" id="play-btn-${i}" style="background: rgba(255,255,255,0.2); border: none; color: #fff; width: 32px; height: 32px; border-radius: 50%; display: flex; align-items: center; justify-content: center; cursor: pointer; flex-shrink: 0;" title="Play/Pause">▶</button>
                <button type="button" onclick="skipAudio('audio-player-${i}', -10)" style="background: rgba(255,255,255,0.2); border: none; color: #fff; width: 32px; height: 32px; border-radius: 50%; display: flex; align-items: center; justify-content: center; cursor: pointer; flex-shrink: 0;" title="Rewind 10 seconds"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"></path><path d="M3 3v5h5"></path></svg></button>
                <button type="button" onclick="skipAudio('audio-player-${i}', 10)" style="background: rgba(255,255,255,0.2); border: none; color: #fff; width: 32px; height: 32px; border-radius: 50%; display: flex; align-items: center; justify-content: center; cursor: pointer; flex-shrink: 0;" title="Fast forward 10 seconds"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"></path><path d="M21 3v5h-5"></path></svg></button>
                <input type="range" id="progress-${i}" value="0" max="100" step="0.1" oninput="seekAudio(${i}, this.value)" style="flex: 1 1 0; min-width: 0; accent-color: #fff; cursor: pointer; height: 4px;">
                <span id="time-${i}" style="font-size: 12px; min-width: 42px; text-align: right; flex-shrink: 0;">0:00</span>
              </div>`;
          } else {
            mediaHtml = `<div style="color:var(--text-muted); font-size:12px;">No media available for this session.</div>`;
          }
          const sessionPresenterHtml = s.presenter ? `
            <div style="display:flex; align-items:center; gap:8px; margin-bottom:6px;">
              <img src="${s.presenter.photo}" alt="${s.presenter.name}" style="width:26px; height:26px; border-radius:50%; object-fit:cover; border:1px solid var(--border-color);">
              <span style="font-size:12px; color:var(--text-muted);">${s.presenter.name}</span>
            </div>` : '';
          const safeSessionTitle = (s.title || '').replace(/'/g, "\\'");
          return `
            <div id="book-session-${originalIndex}" style="margin-bottom:14px;">
              <div style="display:flex; align-items:flex-start; justify-content:space-between; gap:8px; margin-bottom:6px;">
                <div style="font-weight:600; font-size:14px; color:var(--text-main);">${s.title}</div>
                <button class="share-btn" title="Share this resource" style="flex-shrink:0;" onclick="shareBookSession('${safeBookTitle}', ${originalIndex}, '${safeSessionTitle}')">
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8"></path><polyline points="16 6 12 2 8 6"></polyline><line x1="12" y1="2" x2="12" y2="15"></line></svg>
                </button>
              </div>
              ${sessionPresenterHtml}
              ${mediaHtml}
            </div>`;
        }).join('');
      }

      panel.innerHTML = `
        <div style="font-family: var(--font-heading); font-size:28px; color:var(--text-main); margin-bottom:12px;">${cfg.title}</div>
        ${presenterHtml}
        ${typeFilterHtml}
        <div>${sessionsHtml}</div>`;
    }

    // ============================================================
    // BOOKS OF THE BIBLE — ADMIN CONTENT EDITOR
    // Lets an admin add/edit a book's presenters and sessions/articles
    // entirely through form fields, then saves it to the bible_study_books
    // table (see loadBibleStudyBooksFromDB / getBibleStudyBookConfig above).
    // No file editing, no braces to get wrong.
    // ============================================================
    export let bookAdminPresentersState = []; // [{ name, photo }]
    export let bookAdminSessionsState = [];   // [{ title, type, url, presenterName, presenterPhoto }]

    export async function openBookAdminView() {
      if (!currentUser || !currentUser.isAdmin) return;

      document.querySelectorAll('.nav-btn').forEach(btn => btn.classList.remove('active'));
      document.querySelectorAll('.tab-content').forEach(content => content.classList.remove('active'));
      const notifPanel = document.getElementById('reading-notification-panel');
      if (notifPanel) notifPanel.style.display = 'none';

      document.getElementById('book-admin-tab').classList.add('active');

      const select = document.getElementById('book-admin-select');
      select.innerHTML = '<option value="">Choose a book…</option>' +
        BIBLE_STUDIES_BOOK_ORDER.map(title => `<option value="${title}">${title}</option>`).join('');

      await loadStudyPresenters();
      await seedStudyPresentersFromExistingBooksIfEmpty();
      await loadBookShelfGroups();

      // Open straight into whichever book the admin was just looking at, if any.
      if (activeBibleStudyBook) {
        select.value = activeBibleStudyBook;
        handleBookAdminSelectChange();
      } else {
        document.getElementById('book-admin-form').style.display = 'none';
      }
    }

    export function closeBookAdminView() {
      switchTab('study');
    }

    export function handleBookAdminSelectChange() {
      const title = document.getElementById('book-admin-select').value;
      const formEl = document.getElementById('book-admin-form');
      if (!title) { formEl.style.display = 'none'; return; }
      formEl.style.display = 'block';

      const index = BIBLE_STUDIES_BOOK_ORDER.indexOf(title);
      const cfg = getBibleStudyBookConfig(title, index);

      document.getElementById('book-admin-color').value = cfg.color;
      document.getElementById('book-admin-height').value = cfg.height;
      document.getElementById('book-admin-live').checked = cfg.live;
      populateBookAdminShelfGroupSelect(cfg.shelfGroupId);

      bookAdminPresentersState = (cfg.presenters || []).map(p => ({ name: p.name || '', photo: p.photo || '' }));
      bookAdminSessionsState = (cfg.sessions || []).map(s => ({
        title: s.title || '',
        type: getSessionType(s) !== 'other' ? getSessionType(s) : 'audio',
        url: s.audio || s.video || s.article || '',
        presenterName: s.presenter ? (s.presenter.name || '') : '',
        presenterPhoto: s.presenter ? (s.presenter.photo || '') : ''
      }));

      const deleteBtn = document.getElementById('book-admin-delete-btn');
      deleteBtn.style.display = cfg.dbId ? 'inline-block' : 'none';

      renderBookAdminPresenterRows();
      renderBookAdminSessionRows();
    }

    // Fills the Shelf Group dropdown from the current directory, selecting
    // whichever group (if any) the book being edited already belongs to, then
    // syncs the color/height fields and helper note to match via
    // handleBookAdminShelfGroupChange.
    export function populateBookAdminShelfGroupSelect(selectedId) {
      const select = document.getElementById('book-admin-shelf-group');
      if (!select) return;
      select.innerHTML = `<option value="">No group (set this book's own color &amp; height below)</option>` +
        bookShelfGroupsList.map(g => `<option value="${g.id}">${(g.name || '').replace(/</g, '&lt;')}</option>`).join('') +
        `<option value="__new__">+ New group…</option>`;
      select.value = (selectedId != null && bookShelfGroupsList.some(g => g.id === selectedId)) ? String(selectedId) : '';
      handleBookAdminShelfGroupChange();
    }

    // Keeps the color/height fields, their labels, and the helper note in sync
    // with whatever's picked in the Shelf Group dropdown:
    //  - "No group": the fields are this book's own color/height (as before).
    //  - an existing group: the fields show (and, on Save, can edit) that
    //    group's shared color/height — changing them here updates every book
    //    in the group, not just this one.
    //  - "+ New group…": reveals a name field; the color/height set below
    //    become that new group's starting values.
    export function handleBookAdminShelfGroupChange() {
      const select = document.getElementById('book-admin-shelf-group');
      if (!select) return;
      const val = select.value;
      const newNameField = document.getElementById('book-admin-new-group-name-field');
      const note = document.getElementById('book-admin-shelf-group-note');
      const colorLabel = document.getElementById('book-admin-color-label');
      const heightLabel = document.getElementById('book-admin-height-label');
      const deleteGroupField = document.getElementById('book-admin-delete-shelf-group-field');

      if (val === '__new__') {
        newNameField.style.display = 'block';
        note.style.display = 'block';
        note.innerText = 'Creates a new shelf group using the color/height set below — every book you assign to this group (including this one) will share them.';
        colorLabel.innerText = 'Group color';
        heightLabel.innerText = 'Group height (px)';
        if (deleteGroupField) deleteGroupField.style.display = 'none';
      } else if (val) {
        newNameField.style.display = 'none';
        const group = bookShelfGroupsList.find(g => String(g.id) === val);
        if (group) {
          document.getElementById('book-admin-color').value = group.color;
          document.getElementById('book-admin-height').value = group.height;
        }
        note.style.display = 'block';
        note.innerText = `This book is in the "${group ? group.name : ''}" shelf group. Changing the color/height below updates every book in that group at once.`;
        colorLabel.innerText = 'Group color';
        heightLabel.innerText = 'Group height (px)';
        if (deleteGroupField) deleteGroupField.style.display = 'block';
      } else {
        newNameField.style.display = 'none';
        note.style.display = 'none';
        colorLabel.innerText = 'Spine color';
        heightLabel.innerText = 'Spine height (px)';
        if (deleteGroupField) deleteGroupField.style.display = 'none';
      }
    }

    // Removes an entire shelf grouping (not just this one book's membership in
    // it) — the group row itself, never any book. Every book currently in the
    // group falls back to being ungrouped, keeping whatever color/height the
    // group last had as its own individual value from then on
    // (bible_study_books.shelf_group_id is "on delete set null" — see
    // book_shelf_groups_migration.sql — so this is safe even for books other
    // than the one currently open in this form; their content, sessions, and
    // presenters are completely untouched).
    export async function deleteBookAdminShelfGroup() {
      if (!currentUser || !currentUser.isAdmin) return;
      const select = document.getElementById('book-admin-shelf-group');
      const val = select ? select.value : '';
      if (!val || val === '__new__') return;
      const groupId = parseInt(val, 10);
      const group = bookShelfGroupsList.find(g => g.id === groupId);
      if (!group) return;

      const memberBooks = Object.keys(bibleStudyDbBooks).filter(title => bibleStudyDbBooks[title].shelfGroupId === groupId);
      const memberNote = memberBooks.length > 0
        ? `\n\nAffected book(s), unchanged except for this: ${memberBooks.join(', ')}.`
        : '';
      if (!confirm(`Remove the "${group.name}" grouping? This does NOT delete any books or their content — it only breaks the shared color/height link between them. Each book keeps "${group.name}"'s current color and height as its own from now on, just no longer tied together.${memberNote}`)) return;

      const { error } = await bookShelfGroupsTable.remove(groupId);
      if (error) {
        console.error('Error deleting shelf group:', error.message);
        alert('Could not delete the shelf group: ' + error.message);
        return;
      }

      bookShelfGroupsList = bookShelfGroupsList.filter(g => g.id !== groupId);
      // The database already detached every member book (on delete set null) —
      // mirror that in the local cache rather than re-fetching, so this works
      // offline-of-a-reload too.
      memberBooks.forEach(title => { bibleStudyDbBooks[title].shelfGroupId = null; });

      alert(`Removed the "${group.name}" grouping. No books were deleted — they're just ungrouped now, each keeping its last color/height as its own.`);
      renderBibleStudyShelf();
      // Refresh the form for whichever book is currently open — it may have
      // just lost its group.
      handleBookAdminSelectChange();
    }

    export function renderBookAdminPresenterRows() {
      const list = document.getElementById('book-admin-presenters-list');
      if (!list) return;
      if (bookAdminPresentersState.length === 0) {
        list.innerHTML = `<div style="color:var(--text-muted); font-size:13px; margin-bottom:8px;">No presenters yet — sessions will show without a "Presented by" credit until you add one.</div>`;
        return;
      }
      list.innerHTML = bookAdminPresentersState.map((p, idx) => `
        <div class="book-admin-item-card">
          <div class="book-admin-field-row">
            <div style="flex:1 1 100%;">
              <label>Choose an existing presenter</label>
              <select class="input-field study-presenter-picker" style="margin-bottom:0;" onchange="handleBookAdminPresenterPick(${idx}, this.value)">
                <option value="">Choose an existing presenter…</option>
              </select>
              <div class="study-presenter-picker-error-note" style="display:none; color:var(--accent-coral); font-size:12px; margin-top:4px;"></div>
            </div>
          </div>
          <div class="book-admin-field-row">
            <div style="flex:1 1 160px;">
              <label>Name</label>
              <input type="text" class="input-field" style="margin-bottom:0;" value="${(p.name || '').replace(/"/g, '&quot;')}" oninput="updateBookAdminPresenterField(${idx}, 'name', this.value)" placeholder="e.g. Mr. John Ogwyn">
            </div>
            <div style="flex:1 1 220px;">
              <label>Photo URL (or pick a presenter above)</label>
              <input type="text" class="input-field" style="margin-bottom:0;" value="${(p.photo || '').replace(/"/g, '&quot;')}" oninput="updateBookAdminPresenterField(${idx}, 'photo', this.value)" placeholder="https://...">
            </div>
            <div>
              <button type="button" class="page-btn" style="background:#fee2e2; color:#b91c1c; border-color:#fca5a5;" onclick="removeBookAdminPresenterRow(${idx})">Remove</button>
            </div>
          </div>
        </div>`).join('');
      populateStudyPresenterDropdowns();
    }

    // Filling in name + photo from the reusable directory, so an admin picking an
    // existing presenter doesn't have to retype or repaste their photo URL.
    export function handleBookAdminPresenterPick(idx, presenterId) {
      if (!presenterId) return;
      const presenter = studyPresentersList.find(p => String(p.id) === presenterId);
      if (!presenter || !bookAdminPresentersState[idx]) return;
      bookAdminPresentersState[idx].name = presenter.name;
      bookAdminPresentersState[idx].photo = presenter.photo_url;
      renderBookAdminPresenterRows();
    }

    export function addBookAdminPresenterRow() {
      bookAdminPresentersState.push({ name: '', photo: '' });
      renderBookAdminPresenterRows();
    }

    export function removeBookAdminPresenterRow(idx) {
      bookAdminPresentersState.splice(idx, 1);
      renderBookAdminPresenterRows();
    }

    export function updateBookAdminPresenterField(idx, field, value) {
      if (!bookAdminPresentersState[idx]) return;
      bookAdminPresentersState[idx][field] = value;
    }

    export const BOOK_ADMIN_TYPE_PLACEHOLDERS = {
      audio: 'https://... (mp3 link)',
      video: 'https://youtube.com/watch?v=...',
      print: 'https://... (article link)',
      study_guide: 'https://... (study guide/PDF link)'
    };

    export function renderBookAdminSessionRows() {
      const list = document.getElementById('book-admin-sessions-list');
      if (!list) return;
      if (bookAdminSessionsState.length === 0) {
        list.innerHTML = `<div style="color:var(--text-muted); font-size:13px;">No sessions yet — add one above.</div>`;
        return;
      }
      list.innerHTML = bookAdminSessionsState.map((s, idx) => `
        <div class="book-admin-item-card session-drag-card"
             draggable="true"
             ondragstart="handleSessionDragStart(event, ${idx})"
             ondragover="handleSessionDragOver(event, ${idx})"
             ondragleave="handleSessionDragLeave(event)"
             ondrop="handleSessionDrop(event, ${idx})"
             ondragend="handleSessionDragEnd(event)">
          <div class="session-drag-handle" title="Drag to reorder">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><circle cx="8" cy="6" r="1.6"/><circle cx="16" cy="6" r="1.6"/><circle cx="8" cy="12" r="1.6"/><circle cx="16" cy="12" r="1.6"/><circle cx="8" cy="18" r="1.6"/><circle cx="16" cy="18" r="1.6"/></svg>
            <span>Session ${idx + 1}</span>
          </div>
          <div class="book-admin-field-row">
            <div style="flex:1 1 100%;">
              <label>Title</label>
              <input type="text" class="input-field" style="margin-bottom:0;" value="${(s.title || '').replace(/"/g, '&quot;')}" oninput="updateBookAdminSessionField(${idx}, 'title', this.value)" placeholder="e.g. Session 1: Survey of Job">
            </div>
          </div>
          <div class="book-admin-field-row">
            <div style="flex:1 1 120px;">
              <label>Type</label>
              <select class="input-field" style="margin-bottom:0;" onchange="updateBookAdminSessionField(${idx}, 'type', this.value)">
                <option value="audio" ${s.type === 'audio' ? 'selected' : ''}>Audio</option>
                <option value="video" ${s.type === 'video' ? 'selected' : ''}>Video</option>
                <option value="print" ${s.type === 'print' ? 'selected' : ''}>Print (article)</option>
                <option value="study_guide" ${s.type === 'study_guide' ? 'selected' : ''}>Print (Study Guide)</option>
              </select>
            </div>
            <div style="flex:2 1 220px;">
              <label>Content URL</label>
              <input type="text" class="input-field" style="margin-bottom:0;" value="${(s.url || '').replace(/"/g, '&quot;')}" oninput="updateBookAdminSessionField(${idx}, 'url', this.value)" placeholder="${BOOK_ADMIN_TYPE_PLACEHOLDERS[s.type] || ''}">
            </div>
          </div>
          <div class="book-admin-field-row">
            <div style="flex:1 1 100%;">
              <label>Choose an existing presenter (optional override)</label>
              <select class="input-field study-presenter-picker" style="margin-bottom:0;" onchange="handleSessionAdminPresenterPick(${idx}, this.value)">
                <option value="">Choose an existing presenter…</option>
              </select>
              <div class="study-presenter-picker-error-note" style="display:none; color:var(--accent-coral); font-size:12px; margin-top:4px;"></div>
            </div>
          </div>
          <div class="book-admin-field-row">
            <div style="flex:1 1 160px;">
              <label>Presenter name (optional override)</label>
              <input type="text" class="input-field" style="margin-bottom:0;" value="${(s.presenterName || '').replace(/"/g, '&quot;')}" oninput="updateBookAdminSessionField(${idx}, 'presenterName', this.value)" placeholder="Leave blank to use the book's presenter">
            </div>
            <div style="flex:1 1 220px;">
              <label>Presenter photo URL (optional)</label>
              <input type="text" class="input-field" style="margin-bottom:0;" value="${(s.presenterPhoto || '').replace(/"/g, '&quot;')}" oninput="updateBookAdminSessionField(${idx}, 'presenterPhoto', this.value)" placeholder="https://...">
            </div>
            <div>
              <button type="button" class="page-btn" style="background:#fee2e2; color:#b91c1c; border-color:#fca5a5;" onclick="removeBookAdminSessionRow(${idx})">Remove</button>
            </div>
          </div>
        </div>`).join('');
      populateStudyPresenterDropdowns();
    }


    // --- Drag-and-drop reordering of a book's sessions ---
    // Native HTML5 drag/drop on the whole card (grab anywhere, including the handle) —
    // dragging from a text field still just selects text as usual since the browser
    // treats that as a text-drag, not an element-drag.
    export const bookSessionDragReorder = makeAdminDragReorder(() => bookAdminSessionsState, renderBookAdminSessionRows, 'book-admin-sessions-list');

    export function handleSessionDragStart(event, idx) { bookSessionDragReorder.dragStart(event, idx); }
    export function handleSessionDragOver(event, idx) { bookSessionDragReorder.dragOver(event, idx); }
    export function handleSessionDragLeave(event) { bookSessionDragReorder.dragLeave(event); }
    export function handleSessionDrop(event, idx) { bookSessionDragReorder.drop(event, idx); }
    export function handleSessionDragEnd(event) { bookSessionDragReorder.dragEnd(); }

    // Filling in the per-session presenter override from the reusable directory.
    export function handleSessionAdminPresenterPick(idx, presenterId) {
      if (!presenterId) return;
      const presenter = studyPresentersList.find(p => String(p.id) === presenterId);
      if (!presenter || !bookAdminSessionsState[idx]) return;
      bookAdminSessionsState[idx].presenterName = presenter.name;
      bookAdminSessionsState[idx].presenterPhoto = presenter.photo_url;
      renderBookAdminSessionRows();
    }

    export function addBookAdminSessionRow() {
      bookAdminSessionsState.push({ title: '', type: 'audio', url: '', presenterName: '', presenterPhoto: '' });
      renderBookAdminSessionRows();
    }

    export function removeBookAdminSessionRow(idx) {
      bookAdminSessionsState.splice(idx, 1);
      renderBookAdminSessionRows();
    }

    export function updateBookAdminSessionField(idx, field, value) {
      if (!bookAdminSessionsState[idx]) return;
      bookAdminSessionsState[idx][field] = value;
      if (field === 'type') renderBookAdminSessionRows(); // refresh the URL placeholder for the new type
    }

    export async function saveBookAdminForm() {
      if (!currentUser || !currentUser.isAdmin) return;
      const title = document.getElementById('book-admin-select').value;
      if (!title) { alert('Choose a book first.'); return; }

      if (bookAdminSessionsState.some(s => !s.title.trim())) {
        alert('Every session needs a title.');
        return;
      }

      const colorInput = document.getElementById('book-admin-color').value;
      const heightInput = parseInt(document.getElementById('book-admin-height').value, 10) || 195;

      // Resolve the Shelf Group picker into an actual shelf_group_id, creating a
      // new group or propagating an edited color/height to an existing group's
      // other books along the way — see handleBookAdminShelfGroupChange for what
      // each option means.
      const shelfGroupSelectVal = document.getElementById('book-admin-shelf-group').value;
      let shelfGroupId = null;

      if (shelfGroupSelectVal === '__new__') {
        const newGroupName = document.getElementById('book-admin-new-group-name').value.trim();
        if (!newGroupName) { alert('Give the new shelf group a name.'); return; }
        const existingByName = bookShelfGroupsList.find(g => g.name.toLowerCase() === newGroupName.toLowerCase());
        if (existingByName) {
          // Someone already created this group name (maybe in another tab) — join it
          // instead of erroring, propagating this color/height if they've changed.
          shelfGroupId = existingByName.id;
          if (existingByName.color !== colorInput || existingByName.height !== heightInput) {
            const ok = await updateBookShelfGroupColorHeight(shelfGroupId, colorInput, heightInput);
            if (!ok) return;
          }
        } else {
          const { data: newGroup, error: groupError } = await bookShelfGroupsTable.insert(
            { name: newGroupName, color: colorInput, height: heightInput },
            'id, name, color, height'
          );
          if (groupError) {
            console.error('Error creating shelf group:', groupError.message);
            alert('Could not create the shelf group: ' + groupError.message);
            return;
          }
          bookShelfGroupsList.push(newGroup);
          bookShelfGroupsList.sort((a, b) => a.name.localeCompare(b.name));
          shelfGroupId = newGroup.id;
        }
      } else if (shelfGroupSelectVal) {
        shelfGroupId = parseInt(shelfGroupSelectVal, 10);
        const group = bookShelfGroupsList.find(g => g.id === shelfGroupId);
        if (group && (group.color !== colorInput || group.height !== heightInput)) {
          const ok = await updateBookShelfGroupColorHeight(shelfGroupId, colorInput, heightInput);
          if (!ok) return;
        }
      }
      // else: "No group" — shelfGroupId stays null and colorInput/heightInput
      // below are just this one book's own color/height, as before.

      const presenters = bookAdminPresentersState
        .filter(p => p.name.trim())
        .map(p => ({ name: p.name.trim(), photo: p.photo.trim() }));

      const sessions = bookAdminSessionsState.map(s => {
        const item = { title: s.title.trim(), type: s.type };
        if (s.type === 'audio') item.audio = s.url.trim();
        else if (s.type === 'video') item.video = s.url.trim();
        else if (s.type === 'print' || s.type === 'study_guide') item.article = s.url.trim();
        if (s.presenterName.trim()) {
          item.presenter = { name: s.presenterName.trim(), photo: s.presenterPhoto.trim() };
        }
        return item;
      });

      const payload = {
        book: title,
        color: colorInput,
        height: heightInput,
        live: document.getElementById('book-admin-live').checked,
        shelf_group_id: shelfGroupId,
        presenters: presenters,
        sessions: sessions,
        updated_at: new Date().toISOString()
      };

      const { data, error } = await bibleStudyBooksTable.upsert(
        payload,
        'id, book, color, height, live, shelf_group_id, presenters, sessions',
        { onConflict: 'book' }
      );

      if (error) {
        console.error('Error saving book content:', error.message);
        alert('Could not save: ' + error.message);
        return;
      }

      bibleStudyDbBooks[title] = {
        dbId: data.id,
        color: data.color,
        height: data.height,
        live: !!data.live,
        shelfGroupId: data.shelf_group_id,
        presenters: data.presenters || [],
        sessions: data.sessions || []
      };

      // Register any presenter typed in by hand (name + photo, both filled in) into the
      // reusable directory so they show up in the dropdown for every future book.
      for (const p of presenters) {
        await upsertStudyPresenter(p.name, p.photo);
      }
      for (const s of sessions) {
        if (s.presenter && s.presenter.name && s.presenter.photo) {
          await upsertStudyPresenter(s.presenter.name, s.presenter.photo);
        }
      }

      updateStudyNotificationBadges();
      alert(`Saved! "${title}" is now live for everyone.`);
      closeBookAdminView();
      switchStudySubTab('bible-studies');
      selectBibleStudyBook(title, true);
    }

    export async function deleteBookAdminContent() {
      if (!currentUser || !currentUser.isAdmin) return;
      const title = document.getElementById('book-admin-select').value;
      const row = bibleStudyDbBooks[title];
      if (!row) return;
      if (!confirm(`Delete all admin-added content for ${title}? This can't be undone.`)) return;

      const { error } = await bibleStudyBooksTable.remove(row.dbId);
      if (error) {
        console.error('Error deleting book content:', error.message);
        alert('Could not delete: ' + error.message);
        return;
      }

      delete bibleStudyDbBooks[title];
      updateStudyNotificationBadges();
      handleBookAdminSelectChange();
    }

    // One-time migration: copies every book currently hard-coded in BIBLE_STUDIES_DATA
    // into the bible_study_books table, so they become regular database-backed books
    // that show up (and can be edited) here too. Runs in the admin's own browser via the
    // same supabaseClient the rest of the app uses — this is what actually reaches the
    // database, since this session's own sandbox can't call your Supabase project
    // directly (it's blocked by network policy, same as any other outside host).
    // Books already present in the database are left alone, so this is safe to run more
    // than once (e.g. after adding a new hard-coded book later).
    export async function importHardcodedBooksToDB() {
      if (!currentUser || !currentUser.isAdmin) return;

      const titlesToImport = Object.keys(BIBLE_STUDIES_DATA).filter(title => !bibleStudyDbBooks[title]);
      if (titlesToImport.length === 0) {
        alert('Nothing to import — every built-in book is already in the database.');
        return;
      }
      if (!confirm(`Import ${titlesToImport.length} book${titlesToImport.length === 1 ? '' : 's'} into the database?\n\n${titlesToImport.join(', ')}`)) return;

      const rows = titlesToImport.map(title => {
        const custom = BIBLE_STUDIES_DATA[title];
        let presenters = [];
        if (Array.isArray(custom.presenters)) presenters = custom.presenters;
        else if (custom.presenter) presenters = [custom.presenter];
        return {
          book: title,
          color: custom.color || null,
          height: custom.height || null,
          live: !!custom.live,
          shelf_group_id: null, // imported books start ungrouped — an admin can assign one afterward
          presenters: presenters,
          sessions: custom.sessions || [],
          updated_at: new Date().toISOString()
        };
      });

      const { data, error } = await bibleStudyBooksTable.upsertMany(
        rows,
        'id, book, color, height, live, shelf_group_id, presenters, sessions',
        { onConflict: 'book' }
      );

      if (error) {
        console.error('Error importing existing books:', error.message);
        alert('Import failed: ' + error.message + '\n\nMake sure the bible_study_books table has been created in Supabase (see the comment above loadBibleStudyBooksFromDB in this file for the SQL).');
        return;
      }

      (data || []).forEach(r => {
        bibleStudyDbBooks[r.book] = {
          dbId: r.id,
          color: r.color,
          height: r.height,
          live: !!r.live,
          shelfGroupId: r.shelf_group_id,
          presenters: r.presenters || [],
          sessions: r.sessions || []
        };
      });

      updateStudyNotificationBadges();
      renderBibleStudyShelf();
      alert(`Imported ${data ? data.length : titlesToImport.length} book(s). They're now editable from this screen.`);
    }